### ISSUE TITLE
添加/修改/查询iframe支持站点api

### ISSUE THREAD

**Issue by mzz2017** [Actooors/SHU_Message_Service#7]
# 添加/修改/查询iframe支持站点api
## 背景

由于前端使用iframe打开跨域页面，一些web服务器response头含有X-Frame-Options，导致iframe无法正确显示内容，前端攻城狮已经因为这个血拼一整天了，只好想此拙计：
默认使用[iframeForward](https://github.com/mzz2017/iframeForward)进行reverse-proxy，当iframeForward发现该站点response没有X-Frame-Options头时，会调用”添加iframe支持站点“API请求后端接口。这种方法兼容性较好，但无法处理跨域xhr，除非对返回的内容进行侵入性修改，这不是我们想要的，而且反向代理会消耗服务器网络资源，所以我们得尽量少地使用这种方法。

之后会fork一个iframeForward项目到Actooors里来，做一个针对项目的适配。

前端在使用iframe打开跨域页面时，先查询要访问的站点是否属于iframe支持站点，若属于，则直接访问

由于X-Frame-Options头是一种安全措施，不可否认一些站点可能会在将来加入这个措施，因此我们需要一种办法检测站点是否需要移除iframe支持站点，由此来更新iframe支持站点的数据库列表。

### 如何更新

在前端调用查询iframe支持站点api时，后端应当返回一个布尔值，用来标识该站点是否支持iframe，如果支持，前端则直接渲染，如果不支持，则改由iframeForward进行反向代理。

后端应当在该站点支持iframe时，以一定的概率仍然返回false，即让前端误以为不支持iframe，从而由iframeForward进行反代，反代会检测response中的X-Frame-Options属性，决定数据库是否更新。

概率由服务器压力决定，默认设为0.1。

## 添加/更新

不存在则添加，存在则更新

### request

```javascript
{
    host:"http://www.lib.shu.edu.cn",
    support: true
}
```

```javascript
{
    host:"http://www.lib.shu.edu.cn",
    support: false//此时需要从表中删除该项
}
```

### request

```javascript
{
    host:"http://www.lib.shu.edu.cn"
}
```

### response

```javascript
{
    code:"SUCCESS",
    message:null,
    data:{
		exist:true
    }
}
```

**Comment by mzz2017** [comment]
![](http://p6g1c83vx.bkt.clouddn.com//18-8-31/45388938.jpg)

**Comment by 0GGmr0** [comment]
增加的api  /api/common/newIframe

查询 api    /api/common/iframe

**Comment by mzz2017** [comment]
当数据库存在一条iframe时，如果再增加，服务器应该不会增加
